1. Locate open Iris dataset from the URL csv_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
2. Perform the following operation on dataset
a) Display total no of rows and column
b) Display type of each column
c) Sort the data in descending order , by considering column sepal.length
d) Slice the data: 11 to 20 rows, and only two columns, sepal.length and Species
e) rename the column Species to Type

In [1]:
import pandas as pd
import numpy as np    
import matplotlib.pyplot as plt       
import seaborn as sns

In [2]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
col=["sepal_length", "sepal_width", "petal_length", "petal_width", "species"]

In [3]:
df=pd.read_csv(url,names=col,header=None)
df.head(5)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [9]:
df.to_csv("iris.csv",index=False)

Display total no of rows and column

In [ ]:
df.shape

(150, 5)

Display type of each column

In [ ]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

In [ ]:
print(df['sepal_length'],df["sepal_width"],df["petal_length"],df["petal_width"],df["species"])

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64 0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64 0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64 0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal_width, Length: 150, dtype: float64 0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: str

Sort the data in descending order , by considering column sepal.length

In [ ]:

df.sort_values(by="sepal_length",ascending=False,inplace=True)
df

     sepal_length  sepal_width  petal_length  petal_width         species
131           7.9          3.8           6.4          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
..            ...          ...           ...          ...             ...
41            4.5          2.3           1.3          0.3     Iris-setosa
42            4.4          3.2           1.3          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
38            4.4          3.0           1.3          0.2     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa

[150 rows x 5 columns]

Slice the data: 11 to 20 rows, and only two columns, sepal.length and Species

In [ ]:
slice_df = df.loc[10:19, ["sepal_length", "species"]]
slice_df

    sepal_length          species
10           5.4      Iris-setosa
20           5.4      Iris-setosa
16           5.4      Iris-setosa
84           5.4  Iris-versicolor
48           5.3      Iris-setosa
28           5.2      Iris-setosa
32           5.2      Iris-setosa
59           5.2  Iris-versicolor
27           5.2      Iris-setosa
39           5.1      Iris-setosa
44           5.1      Iris-setosa
98           5.1  Iris-versicolor
23           5.1      Iris-setosa
0            5.1      Iris-setosa
19           5.1      Iris-setosa

In [ ]:
sld=df[["sepal_length","species"]]

sld.iloc[10:21]

     sepal_length          species
125           7.2   Iris-virginica
102           7.1   Iris-virginica
50            7.0  Iris-versicolor
52            6.9  Iris-versicolor
120           6.9   Iris-virginica
139           6.9   Iris-virginica
141           6.9   Iris-virginica
112           6.8   Iris-virginica
143           6.8   Iris-virginica
76            6.8  Iris-versicolor
140           6.7   Iris-virginica

 rename the column Species to Type

In [ ]:
df.rename(columns={"species":"sppp"},inplace=True)
df

     sepal_length  sepal_width  petal_length  petal_width            sppp
131           7.9          3.8           6.4          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
..            ...          ...           ...          ...             ...
41            4.5          2.3           1.3          0.3     Iris-setosa
42            4.4          3.2           1.3          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
38            4.4          3.0           1.3          0.2     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa

[150 rows x 5 columns]