In [1]:
import pandas as pd   
import numpy as np          
import seaborn as sns      
import matplotlib.pyplot as plt

In [2]:
data = {
    "gender": ["Male", "Female", "Female", "Male", None, "Female", "Male", None],
    "score": [85, 90, None, 78, 88, None, 92, 75],
    "age": [18, 19, 18, None, 20, 19, None, 18]
}

In [3]:
df=pd.DataFrame(data)
df.head(5)

   gender  score   age
0    Male   85.0  18.0
1  Female   90.0  19.0
2  Female    NaN  18.0
3    Male   78.0   NaN
4     NaN   88.0  20.0

# 1. Check missing values in whole dataframe

In [4]:
df.isnull()

   gender  score    age
0   False  False  False
1   False  False  False
2   False   True  False
3   False  False   True
4    True  False  False
5   False   True  False
6   False  False   True
7    True  False  False

 # 2. Missing values column-wise

In [5]:
df.isnull().sum()

gender    2
score     2
age       2
dtype: int64

# 3. count row wise missing value

In [6]:
df.isnull().sum(axis=1)

0    0
1    0
2    1
3    1
4    1
5    1
6    1
7    1
dtype: int64

# Missing values in gender column

In [7]:
df["gender"].isnull().sum()

np.int64(2)

# Groupby count of missing values (gender & score)

In [8]:
df.groupby("gender")["score"].apply(lambda x:x.isnull().sum())

gender
Female    2
Male      0
Name: score, dtype: int64

# Replace missing values in score column with mean

In [9]:
df["score"]=df["score"].fillna(df["score"].mean(),inplace=True)
df["age"]=df["age"].interpolate()
df["gender"]=df["gender"].ffill()

C:\Users\stidk\AppData\Local\Temp\ipykernel_24488\266302234.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["score"]=df["score"].fillna(df["score"].mean(),inplace=True)

In [10]:
df

   gender      score   age
0    Male  85.000000  18.0
1  Female  90.000000  19.0
2  Female  84.666667  18.0
3    Male  78.000000  19.0
4    Male  88.000000  20.0
5  Female  84.666667  19.0
6    Male  92.000000  18.5
7    Male  75.000000  18.0