1. Load the Academic Performance dataset in data frame object.
2. Check null values in the dataset.
3. Check missing values in dataset and replace the null values with standard null value NaN
4. Replace the missing value of Math Score with Mean Value
5. Replace the missing value of Reading Score with standard deviation
6. Replace the missing value of place with common value "Nashik"

In [69]:
import pandas as pd     
import numpy as np

In [70]:
df=pd.read_csv("StudentsPerformanceTest1.csv")
df.head(5)

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,na
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,Na
4,male,na,78,75.0,81.0,3,Pune

In [71]:
df.isnull().sum()

gender                   0
math score               1
reading score            0
writing score            1
Placement Score          1
placement offer count    0
Region                   1
dtype: int64

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   gender                 9 non-null      str
 1   math score             8 non-null      str
 2   reading score          9 non-null      str
 3   writing score          8 non-null      float64
 4   Placement Score        8 non-null      float64
 5   placement offer count  9 non-null      int64
 6   Region                 8 non-null      str
dtypes: float64(2), int64(1), str(4)
memory usage: 636.0 bytes

In [73]:
df.replace(["na","NaN","null","Na"],np.nan,inplace=True)

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,NaN
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,NaN
4,male,NaN,78,75.0,81.0,3,Pune
5,female,71,NaN,78.0,70.0,4,NaN
6,male,12,44,52.0,12.0,2,Nashik
7,male,NaN,65,67.0,49.0,1,Pune
8,male,5,77,89.0,55.0,0,NaN

In [74]:
df.isnull().sum()

gender                   0
math score               2
reading score            1
writing score            1
Placement Score          1
placement offer count    0
Region                   4
dtype: int64

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   gender                 9 non-null      str
 1   math score             7 non-null      str
 2   reading score          8 non-null      str
 3   writing score          8 non-null      float64
 4   Placement Score        8 non-null      float64
 5   placement offer count  9 non-null      int64
 6   Region                 5 non-null      str
dtypes: float64(2), int64(1), str(4)
memory usage: 636.0 bytes

In [76]:
ndf=df.dropna(subset=["math score"])
ndf["math score"]=ndf["math score"].astype(int)
ms_mean=int(ndf["math score"].mean())
df["math score"]=df["math score"].replace(np.nan,str(ms_mean))
df["math score"]=df["math score"].astype(int)

df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,NaN
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,NaN
4,male,52,78,75.0,81.0,3,Pune
5,female,71,NaN,78.0,70.0,4,NaN
6,male,12,44,52.0,12.0,2,Nashik
7,male,52,65,67.0,49.0,1,Pune
8,male,5,77,89.0,55.0,0,NaN

In [77]:
ndf=df.dropna(subset=["reading score"])
ndf["reading score"]=ndf["reading score"].astype(int)
ms_mean=int(ndf["reading score"].std())
df["reading score"]=df["reading score"].replace(np.nan,str(ms_mean))
df["reading score"]=df["reading score"].astype(int)
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,NaN
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,NaN
4,male,52,78,75.0,81.0,3,Pune
5,female,71,16,78.0,70.0,4,NaN
6,male,12,44,52.0,12.0,2,Nashik
7,male,52,65,67.0,49.0,1,Pune
8,male,5,77,89.0,55.0,0,NaN

In [81]:
df["Region"]=df["Region"].fillna("Nashik",inplace=True)
df

C:\Users\stidk\AppData\Local\Temp\ipykernel_27204\1844103964.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Region"]=df["Region"].fillna("Nashik",inplace=True)

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,Nashik
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,Nashik
4,male,52,78,75.0,81.0,3,Pune
5,female,71,16,78.0,70.0,4,Nashik
6,male,12,44,52.0,12.0,2,Nashik
7,male,52,65,67.0,49.0,1,Pune
8,male,5,77,89.0,55.0,0,Nashik